apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-debug
  template:
    metadata:
      labels:
        app: busybox-debug
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sleep", "3600"]