apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-repo-access
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.secrets.username | b64enc | quote }}
  password: {{ .Values.secrets.password | b64enc | quote }}